version: "3"

services:
  db:
    container_name: db
    image: postgres:13.2
    # latest
    ports:
      - "6297:6297"
    volumes:
      - django_data_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "haljion11"
  webapi:
    container_name: webapi
    build:
      context: Dockerfiles
      dockerfile: dev
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/var/www/src
    tty: true
    ports:
      - 8888:8000
    links:
      - db:db
volumes:
  django_data_volume:
