# Generated by Django 3.2 on 2022-06-30 07:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='ボール名')),
                ('image', models.CharField(max_length=50, verbose_name='画像')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='アイテム名')),
                ('image', models.CharField(max_length=50, verbose_name='画像')),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='性格名')),
                ('up', models.IntegerField(verbose_name='上昇値')),
                ('down', models.IntegerField(verbose_name='下降値')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='種族名')),
                ('image', models.CharField(max_length=50, verbose_name='画像')),
                ('type1', models.CharField(max_length=10, verbose_name='タイプ1')),
                ('type2', models.CharField(blank=True, max_length=10, null=True, verbose_name='タイプ2')),
                ('ability1', models.CharField(max_length=20, verbose_name='特性1')),
                ('ability2', models.CharField(blank=True, max_length=20, null=True, verbose_name='特性2')),
                ('hidden_ability', models.CharField(blank=True, max_length=20, null=True, verbose_name='隠れ特性')),
                ('gender_flag', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='性別有無')),
                ('varioustaH', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='種族値H')),
                ('varioustaA', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='種族値A')),
                ('varioustaB', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='種族値B')),
                ('varioustaC', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='種族値C')),
                ('varioustaD', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='種族値D')),
                ('varioustaS', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='種族値S')),
            ],
        ),
        migrations.CreateModel(
            name='Waza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='わざ名')),
                ('waza_type', models.CharField(max_length=10, verbose_name='タイプ')),
                ('various', models.IntegerField(verbose_name='種類')),
            ],
        ),
        migrations.CreateModel(
            name='UserPoke',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=300, verbose_name='ユーザーID')),
                ('nickname', models.CharField(blank=True, max_length=10, verbose_name='ニックネーム')),
                ('gender', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('color', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ability', models.CharField(max_length=20, verbose_name='特性')),
                ('individual_value_h', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('individual_value_a', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('individual_value_b', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('individual_value_c', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('individual_value_d', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('individual_value_s', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('effort_value_h', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('effort_value_a', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('effort_value_b', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('effort_value_c', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('effort_value_d', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('effort_value_s', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.CharField(blank=True, max_length=300, verbose_name='備考')),
                ('ball', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pokes', to='webapi.ball')),
                ('item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pokes', to='webapi.item')),
                ('personality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pokes', to='webapi.personality')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pokes', to='webapi.pokemon')),
                ('waza1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pokes_1', to='webapi.waza')),
                ('waza2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pokes_2', to='webapi.waza')),
                ('waza3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pokes_3', to='webapi.waza')),
                ('waza4', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pokes_4', to='webapi.waza')),
            ],
        ),
    ]
