# Generated by Django 3.2 on 2022-02-21 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0003_auto_20220208_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='variousta',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='gender_flag',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='性別有無'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='varioustaA',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='種族値A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='varioustaB',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='種族値B'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='varioustaC',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='種族値C'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='varioustaD',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='種族値D'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='varioustaH',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='種族値H'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='varioustaS',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='種族値S'),
            preserve_default=False,
        ),
    ]
