# Generated by Django 3.2 on 2022-03-09 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0004_auto_20220222_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoke',
            name='remarks',
            field=models.CharField(blank=True, max_length=300, verbose_name='ニックネーム'),
        ),
        migrations.AlterField(
            model_name='userpoke',
            name='waza2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pokes_2', to='webapi.waza'),
        ),
        migrations.AlterField(
            model_name='userpoke',
            name='waza3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pokes_3', to='webapi.waza'),
        ),
        migrations.AlterField(
            model_name='userpoke',
            name='waza4',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pokes_4', to='webapi.waza'),
        ),
    ]
