# Generated by Django 3.2 on 2022-03-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0006_alter_userpoke_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoke',
            name='item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pokes', to='webapi.item'),
        ),
    ]
